---

- name: update web server
  hosts: web

  tasks: 
  - name: create a web directory
    file:
     path: /home/centos/web
     state: directory

  - name: to install apache
    yum:
     name: httpd
     state: installed

  - name: to start the httpd
    service: 
     name: httpd
     state: started



...


