---

- name: To run website on web server
  hosts: n2
  become: yes

  tasks: 
  - name: To install git
    yum: 
     name: git
     state: installed

  - name: To install httpd
    yum: 
      name: httpd
      state: installed

  - name: To start the web server with help of git in ansible
    git: 
     repo: https://github.com/ravi2krishna/food.git
     dest: /var/www/html

  - name: To start httpd service
    service: 
      name: httpd
      state: started

...
